config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'container/index'
  get 'container/new'
  post 'container/create'
  get 'container/run'
  get 'container/delete'
  get 'images/index'
  get 'images/new'
  post 'images/create'
  get 'images/delete'
  get 'images/delete_2'

  devise_for :users

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/container.rb
class Container < ApplicationRecord

  attr_accessor :id, :name, :status, :port, :repository, :tag

  # バリデーション処理
  validates :id, length: { is: 12 }
  validates :status, format: { with: /\A(稼働中|停止)\z/ }, allow_blank: true
  validates :repository, length: { maximum: 15 }, format: {with: /\A([A-Za-z0-9]+[A-Za-z0-9_-]+[A-Za-z0-9])\z/}, allow_blank: true
  validates :tag, length: { maximum: 12 }, format: {with: /\A([A-Za-z0-9]+[A-Za-z0-9_-]+[A-Za-z0-9])\z/}, allow_blank: true
  
  def all_container_info()
    ids = `docker ps -a --format "{{.ID}}"`.chomp.split("\n")

    all_container = []
    ids.each do |id|
      container = Container.new()
      container.container_info(id)
      all_container << container
    end
    all_container
  end

  def container_info(id)
    @id = id
    @name = `docker ps -af "id=#{id}" --format '{{.Names}}'`.chomp
    @status = `docker ps -af "id=#{id}" --format '{{.Status}}'`.chomp
    @port = `docker ps -af "id=#{id}" --format '{{.Ports}}'`.chomp
    image_name = `docker ps -af "id=#{id}" --format '{{.Image}}'`.chomp
    if image_name.include?(":")
      @repository = image_name.split(":")[0]
      @tag = image_name.split(":")[1]
    else
      @repository = image_name
      @tag = "latest"
    end
  
    if @status.include?("Up")
      @status = "稼働中"
    else
      @status = "停止"
    end

    return @id, @name, @status, @port, @repository, @tag
  end

  def create_image(id, repository, tag)
    if repository == ""
      result = false
    elsif tag == ""
      tag = "latest"
      `docker commit #{id} #{repository}:#{tag}`
      result = true
    else
      `docker commit #{id} #{repository}:#{tag}`
      result = true
    end
    result
  end

  # 対象コンテナのステータス情報から、コンテナが起動中か停止中かを判別し、起動/停止させる。
  def start_stop_container(id, status)
    before_status = status
    if status.include?("稼働中")
      `docker container stop #{id}`
    else
      `docker container start #{id}`
    end

    # 1秒待って、ステータスが変化しているか確認する。（結果はboolean型で返す）
    `sleep 1`
    container_info(id)
    @status != before_status
  end

  # 対象コンテナIDと一致するコンテナを削除する。
  def delete_container(id)
    container_info(id)
    `docker rm -f #{id}`

    # 削除に成功したかどうかを確認する。（結果はboolean型で返す）
    `sleep 1`
    `docker ps -aqf "id=#{id}"`.chomp.size == 0
  end
  
end

app/controllers/container_controller.rb
class ContainerController < ApplicationController

  # サーバから全てのコンテナ情報を取得する。
  def index
    containers = Container.new()
    @all_container = containers.all_container_info
  end

  # イメージ作成のためのフォームページへ遷移。
  def new
    @container = Container.new(id_params)
    if @container.valid? && @container.container_info(@container.id)
    else
      redirect_back(fallback_location: root_path, danger: "処理に失敗しました。")
    end
  end

  # 指定した情報からイメージを作成する。
  def create
    @container = Container.new(create_image_params)
    if @container.valid? && @container.create_image(@container.id, @container.repository, @container.tag)
      redirect_to images_index_path, success: "イメージを作成しました。"
    else
      redirect_back(fallback_location: root_path, danger: "処理に失敗しました。")
    end
  end

  # 起動中であれば停止、停止中であれば起動させる。
  def run
    @container = Container.new(id_params.merge(status_params))
    if @container.valid? && @container.start_stop_container(@container.id, @container.status)
        flash.now[:success] = "処理に成功しました。現在のコンテナのステータスは「#{@container.status}」です。"
    else
      redirect_back(fallback_location: root_path, danger: "処理に失敗しました。現在のコンテナのステータスは「#{@container.status}」です。")
    end
  end

  # コンテナを削除する。
  # status_paramsはバリデーションを通すために渡している。
  def delete
    @container = Container.new(id_params)
    if @container.valid? && @container.delete_container(@container.id)
      flash.now[:success] = "コンテナの削除に成功しました。"
    else
      redirect_back(fallback_location: root_path, danger: "コンテナの削除に失敗しました。")
    end
  end

  private
  def id_params
    params.permit(:id)
  end

  def status_params
    params.permit(:status)
  end

  def create_image_params
    params.require(:container).permit(:id, :repository, :tag)
  end

end

app/helpers/container_helper.rb
module ContainerHelper
end

app/views/container/delete.html.erb
<h2>対象コンテナ情報</h2>
<div class="row">
  <div class="col-md-12">
    <%= "コンテナID： #{@container.id}" %><br>
    <%= "コンテナ名： #{@container.name}" %><br>
    <%= "現在のステータス： 削除済み" %><br>
    <%= "利用していたポート： #{@container.port}" %><br>
    <%= "コンテナイメージ： #{@container.repository}" %><br>
  </div>
  <div class="col-md-12">
    <br>
    <%= link_to "コンテナ管理画面へ", container_index_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/container/index.html.erb
<h1>コンテナ管理</h1>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>No</th>    
          <th>コンテナID</th>
          <th>コンテナ名</th>
          <th>ステータス</th>
          <th>ポート</th>
          <th>イメージ名</th>
          <th>起動/停止</th>
          <th>イメージ作成</th>
          <th>削除</th>
        </tr>
      </thead>
      <tbody>
        <% @all_container.each_with_index do |container, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= container.id %></td>
            <td><%= container.name %></td>
            <td><%= container.status %></td>
            <td><%= container.port %></td>
            <td><%= "#{container.repository}:#{container.tag}" %></td>
            <% if container.status == "稼働中" %>
              <td><%= link_to "停止", container_run_path(id: container.id, status: container.status), 
                data: { confirm: "#{container.id}（#{container.name}）\nコンテナを停止しますか？" } %></td>
            <% else %>
              <td><%= link_to "起動", container_run_path(id: container.id, status: container.status), 
                data: { confirm: "#{container.id}（#{container.name}）\nコンテナを起動しますか？" } %></td>  
            <% end %>
              <td><%= link_to "作成", container_new_path(id: container.id, status: container.status), 
                data: { confirm: "#{container.id}（#{container.name}）\nイメージを作成しますか？" } %></td>  
            <td><%= link_to "削除", container_delete_path(id: container.id, status: container.status), 
                data: { confirm: "#{container.id}（#{container.name}）\nコンテナを削除しますか？" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-md-12">
    <p>
      ※1 ホストマシン側の受付ポートが同じである場合、コンテナは起動に失敗します。<br>
    </p>
  </div>

  <div class="col-md-12">
    <br><br>
    <%= link_to "更新", container_index_path, class: 'btn btn-primary' %>
  </div> 
</div>

app/views/container/new.html.erb
<div class="row">
  <div class="col-md-offset-4 col-md-4 users-new-container">
    <h2 class="text-center text-white">イメージ作成</h2>
    <%= form_for @container, url: container_create_path do |f| %>
      <div class="form-group">
        <%= f.hidden_field :id, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :イメージ名（最大15文字）, class: 'text-white' %>
        <%= f.text_field :repository, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :タグ（最大12文字）, class: 'text-white' %>
        <%= f.text_field :tag, class: 'form-control' %>
      </div>

      <%= f.submit "作成", class: 'btn-block btn-white col-md-6' %>
    <% end %>
    
    <%= link_to 'キャンセル', container_index_path, class: 'text-white' %>
  </div>

  <div class="col-md-offset-3 col-md-9">
    <br>
    ※1 登録可能な文字は「英文字の大文字と小文字」、「数値」、「-」、「_」のみとなります。<br>
    ※2 最初と最後の文字は「英文字の大文字と小文字」、「数値」にする必要があります。
  </div>
</div>

app/views/container/run.html.erb
<h2>対象コンテナ情報</h2>
<div class="row">
  <div class="col-md-12">
    <%= "コンテナID： #{@container.id}" %><br>
    <%= "コンテナ名： #{@container.name}" %><br>
    <%= "現在のステータス： #{@container.status}" %><br>
    <%= "利用しているポート： #{@container.port}" %><br>
    <%= "コンテナイメージ： #{@container.repository}" %><br>
  </div>
  <div class="col-md-12">
    <br>
    <%= link_to "コンテナ管理画面へ", container_index_path, class: 'btn btn-default' %>
  </div>
</div>