config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'container/index'
  get 'container/new'
  post 'container/create'
  get 'container/run'
  get 'container/delete'
  get 'images/index'
  get 'images/new'
  post 'images/create'
  get 'images/delete'
  get 'images/delete_2'

  devise_for :users

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/image.rb
class Image < ApplicationRecord

  attr_accessor :id, :repository, :tag, :created, :image_size, :port_host, :port_container

  # バリデーション処理
  validates :id, length: { maximum: 12 }, format: {with: /\A([a-z0-9]+)\z/}, allow_blank: true
  validates :repository, length: { maximum: 15 }, format: {with: /\A([A-Za-z0-9]+[A-Za-z0-9_-]+[A-Za-z0-9]|"<none>")\z/}
  validates :tag, length: { maximum: 12 }, format: {with: /\A([A-Za-z0-9]+[A-Za-z0-9_-]+[A-Za-z0-9]|"<none>")\z/}
  validates :image_size, length: { maximum: 10 }, format: {with: /\A([A-Za-z0-9.]+)\z/}, allow_blank: true
  validates :created, length: { maximum: 22 }, format: {with: /\A([A-Za-z0-9 ]+)\z/}, allow_blank: true
  validates :port_host, length: { in: 1..65535 }, allow_blank: true
  validates :port_container, length: { in: 1..65535 }, allow_blank: true

  def all_image_info()
    count = `docker images -q`.chomp.split("\n").count
    all_image = []
    repository_tag = `docker images --format "{{.ID}} {{.Repository}} {{.Tag}} {{.Size}} {{.CreatedSince}}"`.chomp.split("\n")
    repository_tag.each do |repository_tag|
      repository_tag = repository_tag.split(" ")
      id, repository, tag, image_size = repository_tag[0], repository_tag[1], repository_tag[2], repository_tag[3]
      created = repository_tag[4..(repository_tag.size)].join(' ')
      image = Image.new()
      image.image_info(id, repository, tag, image_size, created)
      all_image << image
    end
    all_image
  end

  def image_info(id, repository, tag, image_size, created)
    @id = id
    @repository = repository
    @tag = tag
    @created = created
    @image_size = image_size
    @port_host = ""
    @port_container = ""
    return @id, @repository, @tag, @created, @image_size ,@port_host ,@port_container
  end

  def create_container(repository, tag, port_host, port_container)
    if port_host != "" && port_container != ""
      `docker run -d -it -p #{port_host}:#{port_container} #{repository}:#{tag}`
      result = true
    elsif port_host != "" || port_container != ""
      result = false
    else
      `docker run -d -it #{repository}:#{tag}`
      result = true
    end
    result
  end

  # 対象イメージを削除する。
  def delete_image(id, repository, tag, image_size, created)
    `docker rmi #{repository}:#{tag}`
    # 削除に成功したかどうかを確認する。（結果はboolean型で返す）
    `sleep 1`
    `(docker images --format "{{.Repository}} {{.Tag}}" | grep "^#{repository} #{tag}$")`.split("\n").size == 0
  end

  def delete_unused_image()
    `docker image prune -f`
    # 削除に成功したかどうかを確認する。（結果はboolean型で返す）
    `sleep 1`
    `(docker images --format "{{.Repository}} {{.Tag}}" | grep "<none>")`.split("\n").size == 0
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  # サーバから全てのイメージ情報を取得する。
  def index
    images = Image.new()
    @all_image = images.all_image_info
  end

  def new
    @image = Image.new(image_params)
    if @image.valid?
    else
      redirect_back(fallback_location: root_path, danger: "処理に失敗しました。")
    end
  end

  def create
    @image = Image.new(create_container_params)
    if @image.valid? && @image.create_container(@image.repository, @image.tag, @image.port_host, @image.port_container)
      redirect_to container_index_path, success: "イメージを作成しました。"
    else
      redirect_back(fallback_location: root_path, danger: "処理に失敗しました。")
    end
  end

  # イメージを削除する。
  def delete
    @image = Image.new(image_params)
    if @image.valid? && @image.delete_image(@image.id, @image.repository, @image.tag, @image.image_size, @image.created)
      flash.now[:success] = "イメージの削除に成功しました。"
    else
      redirect_back(fallback_location: root_path, danger: "イメージの削除に失敗しました。")
    end
  end

  def delete_2
    @image = Image.new()
    @image.delete_unused_image
    redirect_back(fallback_location: root_path, success: "削除可能なイメージを削除しました。")
  end

  private
  def image_params
    params.permit(:id, :repository, :tag, :image_size, :created)
  end

  def create_container_params
    params.require(:image).permit(:repository, :tag, :port_host , :port_container)
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/delete.html.erb
<h2>対象イメージ情報</h2>
<div class="row">
  <div class="col-md-12">
    <%= "イメージID： #{@image.id}" %><br>
    <%= "レジストリ名： #{@image.repository}" %><br>
    <%= "タグ名： #{@image.tag}" %><br>
    <%= "作成されてからの時間： #{@image.created}" %><br>
    <%= "サイズ： #{@image.image_size}" %><br>    
    <%= "現在のステータス： 削除済み" %><br>
  </div>
  <div class="col-md-12">
    <br>
    <%= link_to "イメージ管理画面へ", images_index_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/images/index.html.erb
<h1>イメージ管理</h1>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>No</th>    
          <th>イメージID</th>
          <th>レジストリ名</th>
          <th>タグ名</th>
          <th>作成されてからの時間</th>
          <th>サイズ</th>
          <th>コンテナ作成</th>
          <th>削除</th>
        </tr>
      </thead>
      <tbody>
        <% @all_image.each_with_index do |image, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= image.id %></td>
            <td><%= image.repository %></td>
            <td><%= image.tag %></td>
            <td><%= image.created %></td>
            <td><%= image.image_size %></td>

            <% if image.repository != "<none>" && image.tag != "<none>" %>
              <td><%= link_to "作成", images_new_path(id: image.id, repository: image.repository, tag: image.tag,
                image_size: image.image_size, created: image.created), 
                data: { confirm: "#{image.id}（#{image.repository}:#{image.tag}）\nコンテナを作成しますか？" } %></td>
              <td><%= link_to "削除", images_delete_path(id: image.id, repository: image.repository, tag: image.tag,
                image_size: image.image_size, created: image.created), 
                data: { confirm: "#{image.id}（#{image.repository}:#{image.tag}）\nイメージを削除しますか？" } %></td>
            <% else %>
              <td>-</td>
              <td>-</td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-md-12">
    <p>
      ※1 コンテナの作成時に利用されたイメージは、そのコンテナを削除するまで削除できない場合があります。</br>
      ※2 イメージの作成時に利用されたイメージは、そのイメージを削除するまで削除できない場合があります。<br>
      ※3 レポジトリ名かタグ名に「<%= "<none>" %>」がついてるものは以下リンクから一括削除してください。（※1、※2 を満たしている必要があります）<br>
      　　<%= link_to "不要イメージの削除", images_delete_2_path, class: 'btn btn-default btn-customer-1', data: { confirm: "本当に削除しますか？" } %></td>
    </p>
  </div>

  <div class="col-md-12">
    <br><br>
    <%= link_to "更新", images_index_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/images/new.html.erb
<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <h2 class="text-center">コンテナ作成</h2>
    <%= form_for @image, url: images_create_path do |f| %>
      <div class="form-group">
        <%= f.hidden_field :repository, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.hidden_field :tag, class: 'form-control' %>
      </div>
      <div class="form-group form-inline">
        <%= f.label :ホストマシン側の受付ポート（任意、1～65535） %>
        <%= f.text_field :port_host, class: 'form-control ' %>
      </div>
      <div class="form-group form-inline">
        <%= f.label :コンテナ側の受付ポート（任意、1～65535） %>
        <%= f.text_field :port_container, class: 'form-control ' %>
      </div>

      <%= f.submit "作成", class: 'btn-block btn-white col-md-6' %>
    <% end %>
    
    <%= link_to 'キャンセル', images_index_path, class: 'text-white' %>
  </div>

  <div class="col-md-offset-3 col-md-9">
  <br>
    ※1 ホストマシン側とコンテナ側の受付ポートはどちらかのみの設定はできません。<br>
  </div>
</div>