config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'container/index'
  get 'container/new'
  post 'container/create'
  get 'container/run'
  get 'container/delete'
  get 'images/index'
  get 'images/new'
  post 'images/create'
  get 'images/delete'
  get 'images/delete_2'

  devise_for :users

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag('icons/test.jpg') %>
    <title>Study Note</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="top-hero-wrapper">
      <div class="navbar-bk">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
        <% end %>

        <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
          <div class="container">

            <% if user_signed_in? %>
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            <% end %>

            <div class="navbar-header">
              <%= link_to root_path do %>
                <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
              <% end %>
            </div>

            
            <% if user_signed_in? %>
              <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                  <li class="text-center">
                    <%= link_to "ホーム", home_index_path, class:"userList" %>
                  </li>
                  <li class="text-center">
                    <%= link_to "コンテナ", container_index_path, class:"userList" %>
                  </li>
                  <li class="text-center">
                  <%= link_to "イメージ", images_index_path, class:"userList" %>
                  </li>
                  <li class="text-center">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"userList" %>
                  </li>
                </ul>
              </div>
            <% end %>
          </div>
        </nav>
      </div>

      <div class="container top-hero-container">
        <%= yield %>
      </div>

      <div class="footer">
        <div class="container">
          <div class="footer-left">
          <p>このサイトをシェアする</p>
          <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="Study Note" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          </div>
          <div class="footer-right">
            &copy; 2021 Study Note.
          </div>
          <div class="clear"></div>
        </div>
      </div>

      <script>
        $(function(){
          $(".alert").fadeOut(5000);
        });
      </script>

    </div>
  </body>
</html>